# Generated by Django 5.2.7 on 2025-11-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_booking_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
    ]
