# Generated by Django 5.2.7 on 2025-12-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_menu_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='image',
            new_name='imageUrl',
        ),
        migrations.AddField(
            model_name='menu',
            name='isBestSeller',
            field=models.BooleanField(default=False),
        ),
    ]
