# Generated by Django 5.2.7 on 2025-12-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_menu_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('front_desk', 'FRONT_DESK'), ('housekeeping', 'HOUSEKEEPING'), ('maintenance', 'MAINTENANCE'), ('restaurant', 'RESTAURANT'), ('inventory', 'INVENTORY'), ('restaurant_staff', 'RESTUARANT_STAFF')], default='front_desk', max_length=20),
        ),
    ]
