# Generated by Django 5.2.7 on 2025-12-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
